#!/bin/sh
# set -x

# An example hook script to prevent pushing private refs.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>
#
# This hook shows how to prevent push of private refs '*/priv/*'

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

while read local_ref local_sha remote_ref remote_sha
do
    num_priv_refs=`echo "$local_ref" | grep -E '^.*/priv/.*$' | wc -l`

    if [ "$num_priv_refs" != "0" ]
    then
        echo >&2 "Found private $local_ref, not pushing"
        exit 1
    fi
done

exit 0
